/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(movie)'}/allMovies` | `/allMovies`; params?: Router.UnknownInputParams; } | { pathname: `/../components/rating`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/showTimePage` | `/showTimePage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/showTimes` | `/showTimes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/resrvationPage` | `/resrvationPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(movie)'}/moviePage` | `/moviePage`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(movie)'}/allMovies` | `/allMovies`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/rating`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/showTimePage` | `/showTimePage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/showTimes` | `/showTimes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/resrvationPage` | `/resrvationPage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(movie)'}/moviePage` | `/moviePage`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(movie)'}/allMovies${`?${string}` | `#${string}` | ''}` | `/allMovies${`?${string}` | `#${string}` | ''}` | `/../components/rating${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(showtime)'}/showTimePage${`?${string}` | `#${string}` | ''}` | `/showTimePage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(showtime)'}/showTimes${`?${string}` | `#${string}` | ''}` | `/showTimes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(showtime)'}/resrvationPage${`?${string}` | `#${string}` | ''}` | `/resrvationPage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(movie)'}/moviePage${`?${string}` | `#${string}` | ''}` | `/moviePage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(movie)'}/allMovies` | `/allMovies`; params?: Router.UnknownInputParams; } | { pathname: `/../components/rating`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/showTimePage` | `/showTimePage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/showTimes` | `/showTimes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(showtime)'}/resrvationPage` | `/resrvationPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(movie)'}/moviePage` | `/moviePage`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
